language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
cache: cargo
script:
  - cargo build ${FEATURE_FLAGS}
  - cargo test ${FEATURE_FLAGS}
  - cargo doc ${FEATURE_FLAGS}
env:
  -  FEATURE_FLAGS=""
  -  FEATURE_FLAGS="--no-default-features"
  -  FEATURE_FLAGS="--features image"
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
